-- Harshini Gaddam
-- Updated constraints, create database schema

DROP SCHEMA IF EXISTS PIZZERIA;
CREATE SCHEMA PIZZERIA;
USE PIZZERIA;

CREATE TABLE topping(
TopID  INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
TopName VARCHAR(20) NOT NULL,
PerAMT DECIMAL(4,2) NOT NULL,
MedAMT DECIMAL(4,2) NOT NULL,
LgAMT DECIMAL(4,2) NOT NULL,
XLAMT DECIMAL(4,2) NOT NULL,
CustPrice DECIMAL(4,2),
BusPrice DECIMAL(4,2),
MinINVT INT NOT NULL,
CurINVT INT NOT NULL);


CREATE TABLE pizza(
PizzaID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
OrderID INT,
CrustType VARCHAR(20),
Size VARCHAR(20),
PizzaState VARCHAR(20),
PizzaDate DATETIME,
CustPrice DECIMAL(4,2),
BusPrice DECIMAL(4,2));


CREATE TABLE pizzatoppings(
PizzaID INT NOT NULL,
TopID INT NOT NULL,
Isextra BOOLEAN NOT NULL,
PRIMARY KEY(PizzaID,TopID),
CONSTRAINT FOREIGN KEY (PizzaID) REFERENCES pizza(PizzaID)
ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT FOREIGN KEY (TopID) REFERENCES topping(TopID)
ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE baseprice(
BaseSize VARCHAR(20) NOT NULL,
CrustType VARCHAR(20) NOT NULL,
PRIMARY KEY(CrustType,BaseSize),
CustPrice DECIMAL(4,2),
BusPrice DECIMAL(4,2));

CREATE TABLE discount(
DiscountID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
DiscountName VARCHAR(30) NOT NULL,
isPercent BOOLEAN NOT NULL,
Amount DECIMAL(4,2) NOT NULL);


CREATE TABLE pizzadiscount(
PizzaID INT NOT NULL,
DiscountID INT NOT NULL,
PRIMARY KEY(PizzaID,DiscountID),
CONSTRAINT FOREIGN KEY (PizzaID) REFERENCES pizza(PizzaID)
ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT FOREIGN KEY (DiscountID) REFERENCES discount(DiscountID)
ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE customer(
CustID INT UNIQUE PRIMARY KEY NOT NULL AUTO_INCREMENT,
FName VARCHAR(30),
LName VARCHAR(30),
Phone VARCHAR(30),
Address VARCHAR(240));


CREATE TABLE orders(
OrderID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
CustID int ,
CONSTRAINT FOREIGN KEY (CustID) REFERENCES customer(CustID),
OrderTimeStamp TIMESTAMP NOT NULL,
OrderType VARCHAR(30),
isComplete int not null,
BusPrice DECIMAL(4,2),
CustPrice DECIMAL(4,2)); 


CREATE TABLE orderdiscount(
OrderID INT NOT NULL,
DiscountID INT NOT NULL,
PRIMARY KEY(OrderID,DiscountID),
CONSTRAINT FOREIGN KEY (OrderID) REFERENCES orders(OrderID)
ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT FOREIGN KEY (DiscountID) REFERENCES discount(DiscountID)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE dinein(
OrderID INT PRIMARY KEY NOT NULL,
CONSTRAINT FOREIGN KEY (OrderID) REFERENCES orders(OrderID),
TableNum INT NOT NULL
);

CREATE TABLE pickup(
OrderID INT PRIMARY KEY NOT NULL,
CustID INT NOT NULL,
CONSTRAINT FOREIGN KEY (OrderID) REFERENCES orders(OrderID)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (CustID) REFERENCES customer(CustID)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE delivery(
OrderID INT PRIMARY KEY NOT NULL,
CONSTRAINT FOREIGN KEY (OrderID) REFERENCES orders(OrderID),
CustID INT NOT NULL,
FOREIGN KEY (CustID) REFERENCES customer(CustID)
ON DELETE CASCADE ON UPDATE CASCADE,
CustAddress VARCHAR(100) NOT NULL);

